---
- name: Import OS-specific variables.
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'

- name: Ensure keepalived and its dependencies are installed.
  ansible.builtin.package:
    name: "{{ keepalived_packages }}"
    state: present
  when: keepalived_install | bool

- name: Ensure keepalived command line arguments are defined.
  ansible.builtin.template:
    src: keepalived.default
    dest: /etc/default/keepalived
    mode: "0644"
  notify: Restart keepalived

- name: Ensure keepalived.conf is installed.
  ansible.builtin.template:
    src: keepalived.conf
    dest: /etc/keepalived/keepalived.conf
    mode: "0644"
  notify: Restart keepalived

- name: Ensure keepalived is started.
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: true
